# Generated by Django 5.0.6 on 2024-08-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='StudentListAdmin',
            new_name='StudentList',
        ),
        migrations.RenameModel(
            old_name='TeacherListAdmin',
            new_name='TeacherList',
        ),
    ]
