# Generated by Django 5.0.6 on 2024-09-01 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrr', '0003_customsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='jwttoken',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
