# Generated by Django 5.0.6 on 2024-09-08 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrr', '0009_attendance_semester_subject_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.IntegerField(max_length=1)),
                ('day_of_weak', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitrr.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitrr.teacherlist')),
            ],
        ),
    ]
