# Generated by Django 5.0.6 on 2024-09-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitrr', '0010_timetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='day_of_weak',
            new_name='day_of_week',
        ),
    ]
