# Generated by Django 5.0.6 on 2024-09-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrr', '0012_batch_event_alter_timetable_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='year',
        ),
        migrations.AddField(
            model_name='attendance',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mitrr.batch'),
        ),
    ]
