# Generated by Django 5.0.6 on 2024-09-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrr', '0013_remove_attendance_year_attendance_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mitrr.batch'),
        ),
    ]
