# Generated by Django 5.0.6 on 2024-09-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitrr', '0014_studentlist_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='year',
        ),
        migrations.RemoveField(
            model_name='studentlist',
            name='year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
    ]
