# Generated by Django 5.0.6 on 2024-09-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudentList',
        ),
        migrations.DeleteModel(
            name='CustomSession',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
