# Generated by Django 5.0.6 on 2024-09-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_customsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSession',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
